// <auto-generated />
namespace BonTemps.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Lijst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Lijst));
        
        string IMigrationMetadata.Id
        {
            get { return "201410100900502_Lijst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
